"""Independent runtime support for field_core."""

from .runtime import (
    RuntimeConfigError,
    EXPECTED_RUN_EPOCH_PARAMETERS,
    assert_run_epoch_contract,
    assert_scratch_config,
    autocast_context,
    build_optimizer,
    checkpoint_payload,
    config_dict,
    create_scheduler,
    evaluator_from_config,
    instantiate_factory,
    registered_trainable_ids,
    resolve_target,
    run_official_epoch,
)
from .child import (
    DEFAULT_EVALUATOR_TARGET,
    DEFAULT_MODEL_TARGET,
    DEFAULT_PROBE_EPOCHS,
    ProbeRequest,
    install_import_roots,
    materialize_config,
    run_probe_suite,
    run_smoke,
    run_training,
)

__all__ = [
    "RuntimeConfigError",
    "DEFAULT_EVALUATOR_TARGET",
    "DEFAULT_MODEL_TARGET",
    "DEFAULT_PROBE_EPOCHS",
    "EXPECTED_RUN_EPOCH_PARAMETERS",
    "ProbeRequest",
    "assert_run_epoch_contract",
    "assert_scratch_config",
    "autocast_context",
    "build_optimizer",
    "checkpoint_payload",
    "config_dict",
    "create_scheduler",
    "evaluator_from_config",
    "install_import_roots",
    "instantiate_factory",
    "materialize_config",
    "registered_trainable_ids",
    "resolve_target",
    "run_official_epoch",
    "run_probe_suite",
    "run_smoke",
    "run_training",
]
